In [31]:
import numpy as np

print("---Array a---")
a = np.array([1,2,3,4])
print(a)
print("Size = ",a.size)
print("Shape = ",a.shape)
print("Dimension = ",a.ndim)
print("DataType = ",a.dtype)
print(" ")



print("---Array b---")
b = np.array([[1,2],[3,4],[5,6]])
print(b)
print("Size = ",b.size)
print("Shape = ",b.shape)
print("Dimension = ",b.ndim)
print("DataType = ",b.dtype)
print(" ")


print("---Array c---")
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(c)
print("Size = ",c.size)
print("Shape = ",c.shape)
print("Dimension = ",c.ndim)
print("DataType = ",c.dtype)
print(" ")

print("------------------------------------------------------------------------------------")

print("Array a1")
a1 = np.array([[1,2,3,8],[5,4,9,7]])
print(a1)
print(" ")
print("Sorted a1")
print(np.sort(a1))

print(" ")
print("Array a2")
a2 = np.array([[45,87,25,44],[87,64,15,34]])
print(a2)
print(" ")
print("Sorted a2")
print(np.sort(a2))

print("")
print("Concating Both Arrays")
print(np.concatenate((a1,a2)))

print(" ")
a3 = np.zeros(3)
print(a3)

print(" ")
a4 = np.ones(6)
print(a4)


---Array a---
[1 2 3 4]
Size =  4
Shape =  (4,)
Dimension =  1
DataType =  int32
 
---Array b---
[[1 2]
 [3 4]
 [5 6]]
Size =  6
Shape =  (3, 2)
Dimension =  2
DataType =  int32
 
---Array c---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Size =  12
Shape =  (3, 4)
Dimension =  2
DataType =  int32
 
------------------------------------------------------------------------------------
Array a1
[[1 2 3 8]
 [5 4 9 7]]
 
Sorted a1
[[1 2 3 8]
 [4 5 7 9]]
 
Array a2
[[45 87 25 44]
 [87 64 15 34]]
 
Sorted a2
[[25 44 45 87]
 [15 34 64 87]]

Concating Both Arrays
[[ 1  2  3  8]
 [ 5  4  9  7]
 [45 87 25 44]
 [87 64 15 34]]
 
[0. 0. 0.]
 
[1. 1. 1. 1. 1. 1.]


In [42]:
print("Randomaly Created Array using random.rand()")
a = np.random.rand(2,5)
print(a)

print("")
print("Creating Array using arange()")
b = np.arange(5)
print(b)
b1 = np.arange(5,10)
print("b1 = ",b1)
b2 = np.arange(2,12,2)
print("b2 = ",b2)
b3 = np.arange(8,0,-2)
print("b3 = ",b3)

Randomaly Created Array using random.rand()
[[0.09775737 0.99116045 0.11039556 0.58561215 0.64365767]
 [0.21823335 0.56515324 0.12161285 0.41005623 0.29189125]]

Creating Array using arange()
[0 1 2 3 4]
b1 =  [5 6 7 8 9]
b2 =  [ 2  4  6  8 10]
b3 =  [8 6 4 2]


In [41]:
print("Creating array using linspace()")
a = np.linspace(1,4,8,0)
print("a = ",a)

Creating array using linspace()
a =  [1.    1.375 1.75  2.125 2.5   2.875 3.25  3.625]


In [47]:
a = np.array([1,2,3,4,5])
print(a[2])
print(a[-3])
print(a[1:3])
print(a[:3])
print(a[2:])
print(a[:])

3
3
[2 3]
[1 2 3]
[3 4 5]
[1 2 3 4 5]


In [49]:
a =np.array([
                [1,2,3,4,5],
                [6,7,8,9,10]])
print(a[1,2])
print("")
print(a[0:2,0:3])
print("")
print(a[:,:3])
print("")

print(a[1:,:])
print("")
print(a[:,:])

8

[[1 2 3]
 [6 7 8]]

[[1 2 3]
 [6 7 8]]

[[ 6  7  8  9 10]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [53]:
print("Mathematics opertaion on Arrays")
print(" ")
print("Array 1")
a = np.array([1,2,3,4])
print(a)

print(" ")
print("Array 2")
b = np.array([5,6,7,8])
print(b)

print(" ")
print("Addition = ",a+b)
print("Subtraction = ",a-b)
print("Multiplication = ",a*b)
print("Division = ",a/b)
print(" ")
print("Maximum of A = ",np.max(a))
print("Minimum of B = ",np.min(b))

a1 = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10]])
print(" ")
print("2 Dim Array",a1)
print(np.max(a1[0:1]))

Mathematics opertaion on Arrays
 
Array 1
[1 2 3 4]
 
Array 2
[5 6 7 8]
 
Addition =  [ 6  8 10 12]
Subtraction =  [-4 -4 -4 -4]
Multiplication =  [ 5 12 21 32]
Division =  [0.2        0.33333333 0.42857143 0.5       ]
 
Maximum of A =  4
Minimum of B =  5
 
2 Dim Array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5


In [58]:
print("Array 1")
a = np.array([1,2,3,4,5])
print(a)

print(" ")
print("Array 2")
b = np.array([5,6,7,8])
print(b)

print(" ")
print(a[(a > 2) & (a < 11)])
print(" ")

print(b[(b > 9) | (b == 5)])

Array 1
[1 2 3 4 5]
 
Array 2
[5 6 7 8]
 
[3 4 5]
 
[5]
